api:
    prefix: auth-api
    port: 3001

jwt:
    accessTokenExpiresIn: 15m
    refreshTokenExpiresIn: 30d

roles:
    admin: admin
    user: user

admin:
    # admin email
    email: admin@test.dev

access:
    # roles for access to
    modules:
        # module name
        user: [admin]
        role: [admin]

app:
    # url for api
    baseUrl: http://localhost:3001
    # url for frontend
    frontendUrl: https://smargelov.com
    brand: Auth API

mail:
    host: smtp.yandex.ru
    port: 465
