export const USER_ALREADY_EXISTS = 'User with this email already exists'
export const USER_NOT_FOUND = 'User not found'
export const USER_DELETED_MESSAGE = 'User deleted'
export const FAILED_TO_CREATE_USER = 'Failed to create user'
export const FAILED_TO_UPDATE_USER = 'Failed to update user'
export const FILED_PASSWORD_COMPARE = 'Failed to compare passwords'
export const FILED_EMAIL_CONFIRMATION_TOKEN = 'Email confirmation token is invalid'
