export const AUTH_VALIDATE_ERROR_MESSAGE = 'Invalid email or password'
export const AUTH_NO_REFRESH_TOKEN = 'No refresh token'
export const AUTH_REFRESH_TOKEN_EXPIRED_OR_INVALID = 'Refresh token expired or invalid'
export const RESET_PASSWORD_LINK_SENT = 'Reset password link sent'
export const PASSWORD_CHANGED_NOT_ALLOWED = 'Password changed not allowed'
export const PASSWORD_CHANGED_SUCCESSFULLY = 'Password changed successfully'
